### ISSUE TITLE
Getting "There is no active transaction (Abstract.php:305)" Error when running the Kickstart Wizard

### ISSUE THREAD

**Issue by Cuvo** [Icinga/icingaweb2-module-director#1243]
## Current Behavior

We have zones and endpoints configured in "/etc/icinga2/zones.conf" which are then deployed by using the kickstart wizard in director.
When running the kickstart wizard we get the Error: "There is no active transaction (Abstract.php:305)"
It doesn't matter if we add zones/endpoints to the zones.conf or just running the wizard with the existing zones.conf.
kickstart.ini is configured.
api user is configured.

![2017-10-17 15_29_57-icinga web](https://user-images.githubusercontent.com/25362925/31670480-fec1c10c-b357-11e7-84d5-7f88e4474f53.png)

## Steps to Reproduce (for bugs)

1. Press the "Run import" Button in director

## Context

Cannot add new zone and endpoint to configuration.

## Your Environment

* Director version (System - About): 1.4.0
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): r2.7.1-1
* Operating System and version: CentOS Linux release 7.4.1708
* Webserver, PHP versions: 
PHP: 5.4.16-42.el7
httpd: 2.4.6-67.el7.centos.5

**Comment by NeverUsedID** [comment]
Same here. Worked yesterday. I have cleaned the icinga config on console, and now i get the same error message. Is there any way to get more information out of the director error message ?

**Comment by Cuvo** [comment]
Problem solved with Director Update to 1.4.1:
Please close the issue.


Director version (System - About): 1.4.1
Icinga Web 2 version and modules (System - About): 2.4.2
Icinga 2 version (icinga2 --version): r2.7.1-1
Operating System and version: CentOS Linux release 7.4.1708
Webserver, PHP versions:
PHP: 5.4.16-42.el7
httpd: 2.4.6-67.el7.centos.5

**Comment by NeverUsedID** [comment]
Its not solved on my side. I was already on 1.4.1 and upgraded icingweb2 to 2.4.2 now but still the same result.

**Comment by Thomas-Gelf** [comment]
Could you please show what your DB resource configuration looks like? Any special flag like "use persistent connections"?

**Comment by NeverUsedID** [comment]
Persistent connections was enabled. Disabled it, now its working. Thanks a lot.

**Comment by Thomas-Gelf** [comment]
You're welcome. Persistent connections are a dangerous and buggy beast, shouldn't be used unless one has a very clear picture of what it does and what side-effects it can have.
