### ISSUE TITLE
Offset between timeperiod and deployment time

### ISSUE THREAD

**Issue by swizzly** [Icinga/icingaweb2-module-director#1540]
## Current Behavior
I have some jobs defined in director, that are executed automatically at a given time Time periods. The Problem is, that it seems, that the jobs are getting executed with an two hour offset relative to the defined Time periods. E.g. there is a time period like this "9:00-11:30,13:30-15:00" then the job gets executed only after 11:00 local time.
In the Deployment Logs in Director, the time stamp has also the same offset, e.g. if the above job gets executed at 11:00 local time (though it should have been triggered at 9:00), a new log entry is created with a time stamp of "9:00".
Manually triggered Sync Jobs generate Log entries with the normal local time stamps, without any offset.

## Expected Behavior
Director should execute jobs at the defined time defined in time range in local time, it should display the time periods according to the local timezone, or indicate explicitly that the time ranges are in UTC.

## Possible Solution
Store time ranges in UTC and display them in Icingaweb2 either explicitly marking UTC or calculate the time ranges in local time zone according to the time zone of the PC. The jobs should be then executed in UTC.

## Your Environment
Local Timezone: UTC+01:00 Berlin, etc.
Icinga2 - icinga2-2.8.4-1.el7.icinga.x86_64
Icingaweb2 - icingaweb2-2.5.1-1.el7.icinga.noarch
Director - Icinga-icingaweb2-module-director-v1.4.0-253-gfc58e50.tar.gz

**Comment by Thomas-Gelf** [comment]
@swizzly: I pushed related fixes to the master, could you please give them a try?

**Comment by swizzly** [comment]
Hi Tom,
I installed the current version of director (5059121), but it still does not want to work.
What I did:
- installed newest director version
- applied pending schema changes
- restarted director-jobs.service
- restarted icinga2.service
- adapted the Deployment times period, to be in a current time window
- made some changes on some host objects
- wait ... and nothing happened

**Comment by dgoetz** [comment]
This one should be fixed with https://github.com/Icinga/icingaweb2-module-director/pull/1840 which will be released with 1.7.0.

**Comment by Thomas-Gelf** [comment]
Talked to @swizzly, this now works for him.
