### ISSUE TITLE
Can no longer edit Custom Properties on Inherited Service

### ISSUE THREAD

**Issue by leeclemens** [Icinga/icingaweb2-module-director#1602]
## Expected Behavior
Expected result (v1.4.3 behavior) is an editable form with the overridable Custom properties (and their values pre-filled) and an "Override vars" button.

## Current Behavior
With v1.5.0, there are no fields listed and only a button "Blacklist" is displayed.

## Steps to Reproduce (for bugs)
Icinga Director > Hosts > Hosts > _`Hostname`_ > Services tab
Under "Inherited from _`Host Group`_", click the service

Custom Properties
Message: "This service has been inherited from _`Host Group`_. Still, you might want to change the following properties for this host only."

I compared `apply Service` and `object Host` before and after upgrade and they are identical.

The overridden values are also not functionally working - as missing customized passwords and URLs caused checks to start alerting after the Director upgrade and re-deployment.

```
apply Service "mysql" {
    import "mysql"

    assign where "Some Host Group" in host.templates
    vars.mysql_hostname = "dbserver"
    vars.mysql_password = "dbpass"
    vars.mysql_username = "dbuser

    import DirectorOverrideTemplate
}

object Host "my-host" {
    import "Some Host Group"

    address = "myip"
    vars["_override_servicevars"] += {
        mysql = {
            mysql_hostname = "dbserver2"
            mysql_password = "dbpass2"
            mysql_username = "dbuser2"
        }
    }
}
```

This may be related to some other override properties related bugs, but none that I saw mentioned the form also being blank and others may have been related to Icinga2 versions (everything seems fine as long as I don't upgrade Director from v1.4.3 to v1.5.0).

## Your Environment

* Director version (System - About):
> v1.4.3 (good)
> v1.5.0 (bad)
* Icinga Web 2 version and modules (System - About):
> 2.6.1
> b3e0b5d587c3587a09d82b3634dbe3a5dd315353
> 2018-08-02
* Icinga 2 version (`icinga2 --version`):
> r2.9.1-1
> Compiler: GNU 4.8.5
* Operating System and version:
>  Platform: CentOS Linux
> Platform version: 7 (Core)
> Kernel: Linux
> Kernel version: 3.10.0-862.9.1.el7.x86_64
> Architecture: x86_64
* Webserver, PHP versions:
> Apache 2.4.34
> PHP 7.1.8 (fpm-fcgi) (built: Aug  9 2017 13:21:53)

**Comment by Thomas-Gelf** [comment]
Could you please double-check this? Works fine here. I went the same click-path, picked a host that inherited a service assigned to one of it's templates, fields are there, overriding values works as expected.

**Comment by Thomas-Gelf** [comment]
Please let me also know which fields have been assigned where (Template, Command...)

**Comment by leeclemens** [comment]
No problem, I upgraded to v1.5.0 again and encountered the same issue.

I may have previously used "Host Group" and "Host Template" incorrectly.

```
# Command was imported
object CheckCommand "mysql" {
    import "plugin-check-command"
    command = [ PluginDir + "/check_mysql" ]
    timeout = 1m
...
}

# Service Template has the Fields defined: Password, SSL and Username are required
template Service "mysql" {
    import "Icinga2 Agent Service"

    check_command = "mysql"
    vars.mysql_ssl = false
}


# Host Template has Individual Service objects added to it
template Host "MySQL Client" {
}

# Default values are assigned here since the fields are required
apply Service "mysql" {
    import "mysql"

    assign where "MySQL Client" in host.templates
    vars.mysql_hostname = "dbserver"
    vars.mysql_password = "dbpass"
    vars.mysql_username = "dbuser

    import DirectorOverrideTemplate
}

# Values are overridden on specific hosts that import the Template (and hence have the Service applied) but require different values - this is where the form is missing after upgrading and the checks alert...even though the `_override_servicevars` is still shown in Preview
object Host "my-host" {
    import "MySQL Client"

    address = "myip"
    vars["_override_servicevars"] += {
        mysql = {
            mysql_hostname = "dbserver2"
            mysql_password = "dbpass2"
            mysql_username = "dbuser2"
        }
    }
}
```

I hope that helps, please let me know if any additional info/clarification would help.

**Comment by Thomas-Gelf** [comment]
@leeclemens: Overrides are offered only when there are related Data Fields attached to either your Service Templates or Check Commands. Which Fields of what Data Type do you have attached where? I'll try to reproduce your exact scenario, all attempts I made work just fine

**Comment by leeclemens** [comment]
@Thomas-Gelf the Fields are defined on the Service Template

**Comment by Thomas-Gelf** [comment]
Same here, works fine. ?!?

**Comment by Thomas-Gelf** [comment]
Btw, I missed your above inline comment mentioning the fields - sorry for that

**Comment by Thomas-Gelf** [comment]
@leeclemens: I think I got it. Could you please rename your mysql Template and give it a name different than the Apply Rules name (not `mysql`)?

**Comment by leeclemens** [comment]
@Thomas-Gelf no worries...I renamed the Service Template and the Apply Rule to different (from `mysql` and each other) names and the form fields appear.

However, the checks are still failing and viewing them in Icingaweb2 Service tab and the light/default in the form field show to inherited values...not the overridden values (maybe another issue):

```
    vars["_override_servicevars"] += {
        mysql = {
            mysql_hostname = "dbhost2"
            mysql_password = "dbpass2"
            mysql_username = "dbuser2"
        }
    }
```

**Comment by Thomas-Gelf** [comment]
Ok, we're getting closer. When you rename your Apply Rule to `mysql` and the Template to `anything`, then the values appear I guess?

**Comment by Thomas-Gelf** [comment]
-> deleting/renaming Services has no effect on old overrides, they stay there, do not follow the service, rest orphaned, there is no cleanup. A related issue exists, will sooner or later be addressed - that's a compromise we live with right now. I mention it only to get you a better understanding of what's going on.

What we figured out until now is: when the Apply Rule has the same name as the Template fields are not shown. This could be related to the Template Resolving Tree, I'll check this. What I want from you is: are there (apart from the overrides not following your rename actions) still other problems when you keep the template name different?

**Comment by leeclemens** [comment]
Yes, that is correct. Renaming only the Template, the form appears and has the previously overridden values pre-populated and two buttons (override/blacklist). Icingaweb2 Service tab shows the old/default values under Custom Variables.

**Comment by Thomas-Gelf** [comment]
Ok, cool. Thanks a lot for your time. So, the issue is "Custom Fields are not shown for Apply Rules when the Apply Rule name equals the Service Template name". Will track this down and fix it, in the meantime we have a workaround.

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
@leeclemens: I pushed a fix, could you please give it a try?

**Comment by leeclemens** [comment]
@Thomas-Gelf I upgraded again after having reverted the db, and the same issue occurs with this commit

**Comment by leeclemens** [comment]
@Thomas-Gelf sorry, I should clarify that this specific issue (the form not being displayed properly) is corrected with this fix. The checks still fail, however.

**Comment by Thomas-Gelf** [comment]
@leeclemens: glad to hear that the form works fine. Please explain what do you mean by "the check fails"!

**Comment by Thomas-Gelf** [comment]
@leeclemens: I pushed a fix for #1601 - could you please check whether that one addresses your "check fails" problem?

**Comment by Thomas-Gelf** [comment]
Glad to hear that, thank you for your patience while troubleshooting this issue!
