### ISSUE TITLE
Authentication director/filter/hostgroups doesnt work for inherit groups

### ISSUE THREAD

**Issue by tgruenert** [Icinga/icingaweb2-module-director#1663]
## Expected Behavior
Please use inherit information from templates also as a criteria in filters at role definition.

## Current Behavior
Filter on hostgroup in a role work only if hostgroup is set directly inside host definition.

## Steps to Reproduce (for bugs)

1. Define a host X based on a host template Xt. Host template is member of group A. So as far as i unterstand the host X is also member of hostgroup A. At GUI this is shown as inherit group. Nice feature.
2. I define a role with filter director/filter/hostgroups=A.
3. The user U based on this role see no hosts in director.
4. Change Host X and set hostgroup directly to A.
5. User U see the host inside director as expected.

## Environment
icinga2 --version
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.9.1-1)
System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.17.0-0.bpo.3-amd64
  Architecture: x86_64
.........
Build information:
  Compiler: GNU 6.3.0
  Build host: 83e7f59f33f0

```

Disabled features: debuglog elasticsearch gelf influxdb opentsdb perfdata statusdata syslog
Enabled features: api checker command compatlog graphite ido-mysql livestatus mainlog notification

**Comment by Thomas-Gelf** [comment]
This used to be a problem, but should work fine right now. What Director version are you using?

**Comment by tgruenert** [comment]
gui show "master". it is deployd via docker from https://hub.docker.com/r/jordan/icinga2/ at 2018-08-11
hope this helps.

**Comment by cbuehrer** [comment]
Hi, 
i have the same problem. (Director version 1.6.2) 

- User in a role restricted to a single hostgroup (director/filter/hostgroups = "hostgrp_something")
- Template defines hostgroup (groups = [ "hostgrp_something" ])
- User tries to create a new host choosing the template.
- Fails with: Unable to store a host with the given properties because of insufficient permissions (IcingaHostForm.php:363)

Any help would be highly appreciated 
Christof

**Comment by slaveeu** [comment]
I had a similar problem .  The code section from IcingaHostForm.php  

> if (! $restriction->allowsHost($this->object())) {
                throw new AuthenticationException($this->translate(
                              'Unable to store a host with the given properties because of insufficient permissions'
     ));
}

throws an exception in this scenarion because:

- it is a newly defined host
- has no associated group, therefore $host->hasModifiedGroups() will reply false 

A possible workarround might be to update function allowsHost from file  HostgroupRestriction.php

> public function allowsHost(IcingaHost $host)
    {
        if (! $this->isRestricted()) {
            return true;
        }
        if (! $host->hasBeenLoadedFromDb()) {
            **$host->setGroups($host->listInheritedGroupNames());**
            if ($host->hasModifiedGroups()) {
                foreach ($this->listRestrictedHostgroups() as $group) {
...

**Comment by Thomas-Gelf** [comment]
This should now work, otherwise please let me know.

**Comment by ziirish** [comment]
Hello,

I'm using director module v1.7.2 and I'm still encountering the same issue as @cbuehrer 
I can provide screenshots if that can be of any help.

As a reminder, steps to reproduce are:

- User in a role restricted to a single hostgroup (director/filter/hostgroups = "hostgrp_something")
- Template defines hostgroup (groups = [ "hostgrp_something" ])
- User tries to create a new host choosing the template.
- Fails with: Unable to store a host with the given properties because of insufficient permissions (IcingaHostForm.php:363)

Thanks

**Comment by mdkamijo** [comment]
@Thomas-Gelf I'm using the same version as @ziirish and get the same result. Was the fix for this issue not included in the last version or is there something else causing this now? Don't know if it's worth replying here or if a new issue should be created?

**Comment by slaveeu** [comment]
Just to confirm that with the same director version and I am also encounter the same issue
