### ISSUE TITLE
PHP errors opening Icinga Director 

### ISSUE THREAD

**Issue by Ramshield** [Icinga/icingaweb2-module-director#2532]
## Current Behavior
https://<HOSTNAME>/director/dashboard?name=hosts gives:
```
Fatal error
: Declaration of Icinga\Module\Director\Dashboard\Dashboard::count() must be compatible with ipl\Html\HtmlDocument::count(): int in
/usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php
on line
20
```

https://<HOSTNAME>/director/config/deployments gives: 
```
Fatal error
: Declaration of gipfl\IcingaWeb2\Table\QueryBasedTable::count() must be compatible with ipl\Html\HtmlDocument::count(): int in
/usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/QueryBasedTable.php
on line
18
```

## Your Environment

* Director version (System - About): master (commit 4692b28dbd720912fb8684a0641355564c439b78)
* Icinga Web 2 version and modules (System - About):
```
director		master
icingadb		0.0.0 (master; 078507122d0b39e1aac34856c35d6fd3b939c94a)
incubator		0.13.0
ipl		0.0.0 (snapshot/nightly from 05/05/2022)
monitoring		2.10.1
reactbundle		0.0.0 (v0.11.0, no clue why it isn't shown here)
```
* Icinga 2 version (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.3-1)

Copyright (c) 2012-2022 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 10 (buster)
  Kernel: Linux
  Kernel version: 5.13.19-2-pve
  Architecture: x86_64

Build information:
  Compiler: GNU 8.3.0
  Build host: runner-hh8q3bz2-project-298-concurrent-0
  OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```
* Operating System and version:
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
* Webserver, PHP versions:
```
# dpkg -l | grep php
ii  icinga-php-common                    1.0.0-1.buster                          all          Icinga PHP Common for Icinga Web 2
ii  icinga-php-library                   0.8.1+4+gb5c5a8b.20220429.1708+buster-0 all          Icinga PHP Library for Icinga Web 2
ii  icinga-php-thirdparty                0.10.0-2.buster                         all          Icinga PHP Thirdparty for Icinga Web 2
ii  libapache2-mod-php                   2:7.3+69                                all          server-side, HTML-embedded scripting language (Apache 2 module) (default)
ii  libapache2-mod-php7.3                7.3.31-1~deb10u1                        amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  php                                  2:7.3+69                                all          server-side, HTML-embedded scripting language (default)
ii  php-common                           2:69                                    all          Common files for PHP packages
ii  php-curl                             2:7.3+69                                all          CURL module for PHP [default]
ii  php-gd                               2:7.3+69                                all          GD module for PHP [default]
ii  php-icinga                           2.10.1-1.buster                         all          PHP library to communicate with and use Icinga
ii  php-igbinary                         3.0.0-1                                 amd64        igbinary PHP serializer
ii  php-imagick                          3.4.3-4.1                               amd64        Provides a wrapper to the ImageMagick library
ii  php-intl                             2:7.3+69                                all          Internationalisation module for PHP [default]
ii  php-ldap                             2:7.3+69                                all          LDAP module for PHP [default]
ii  php-mysql                            2:7.3+69                                all          MySQL module for PHP [default]
ii  php-pear                             1:1.10.6+submodules+notgz-1.1+deb10u2   all          PEAR Base System
ii  php-redis                            4.2.0-1                                 amd64        PHP extension for interfacing with Redis
ii  php-soap                             2:7.3+69                                all          SOAP module for PHP [default]
ii  php-xml                              2:7.3+69                                all          DOM, SimpleXML, WDDX, XML, and XSL module for PHP [default]
ii  php7.3                               7.3.31-1~deb10u1                        all          server-side, HTML-embedded scripting language (metapackage)
ii  php7.3-cli                           7.3.31-1~deb10u1                        amd64        command-line interpreter for the PHP scripting language
ii  php7.3-common                        7.3.31-1~deb10u1                        amd64        documentation, examples and common module for PHP
ii  php7.3-curl                          7.3.31-1~deb10u1                        amd64        CURL module for PHP
ii  php7.3-dev                           7.3.31-1~deb10u1                        amd64        Files for PHP7.3 module development
ii  php7.3-gd                            7.3.31-1~deb10u1                        amd64        GD module for PHP
ii  php7.3-intl                          7.3.31-1~deb10u1                        amd64        Internationalisation module for PHP
ii  php7.3-json                          7.3.31-1~deb10u1                        amd64        JSON module for PHP
ii  php7.3-ldap                          7.3.31-1~deb10u1                        amd64        LDAP module for PHP
ii  php7.3-mbstring                      7.3.31-1~deb10u1                        amd64        MBSTRING module for PHP
ii  php7.3-mysql                         7.3.31-1~deb10u1                        amd64        MySQL module for PHP
ii  php7.3-opcache                       7.3.31-1~deb10u1                        amd64        Zend OpCache module for PHP
ii  php7.3-readline                      7.3.31-1~deb10u1                        amd64        readline module for PHP
ii  php7.3-soap                          7.3.31-1~deb10u1                        amd64        SOAP module for PHP
ii  php7.3-xml                           7.3.31-1~deb10u1                        amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  pkg-php-tools                        1.37                                    all          various packaging tools and scripts for PHP packages
```

**Comment by lippserd** [comment]
Hi,

I'll be merging Icinga/ipl-html#62 so using the next nightly build of the IPL should fix it.

All the best,
Eric

**Comment by Ramshield** [comment]
Hi @lippserd. Thanks for your commit. I changed it manually in `modules/ipl/vendor/ipl/html/src/HtmlDocument.php`  but still getting the same errors.

**Comment by lippserd** [comment]
You should disable the ipl module as it is provided via the package icinga-php-library.

**Comment by Ramshield** [comment]
My apologies @lippserd I did a fresh install, but according to https://icinga.com/docs/icinga-db/latest/icinga-db-web/doc/02-Installation/ I need [Icinga PHP Library (ipl)](https://github.com/Icinga/icinga-php-library) (>= 0.9)
[Icinga PHP Thirdparty](https://github.com/Icinga/icinga-php-thirdparty) (>= 0.11), and that's cute, but the repository only has the following versions:
```
icinga-php-library/icinga-bullseye,now 0.8.1-1.bullseye all [installed,automatic]
icinga-php-thirdparty/icinga-bullseye,now 0.10.0-2.bullseye all [installed,automatic]
```

I follow the official guide and only have the main repository (not testing or snapshot) enabled:
```
deb https://packages.icinga.com/debian icinga-bullseye main
deb-src https://packages.icinga.com/debian icinga-bullseye main
```

So what am I doing wrong, or what is wrong according to the installation guide(s)?
I followed https://icinga.com/docs/icinga-2/latest/doc/02-installation/01-Debian/#install-icinga-2 until Icingaweb2, then https://icinga.com/docs/icinga-web-2/latest/doc/02-Installation/01-Debian/ and for IcingaDB I followed https://icinga.com/docs/icinga-db/latest/icinga-db-web/doc/02-Installation/ (Although this wasn't really useful, but I installed IcingaDB with (https://icinga.com/docs/icinga-web-2/latest/doc/08-Modules/#installation)
```
MODULE_NAME="icinga"
MODULE_VERSION="v1.0.0-rc2"
MODULE_AUTHOR="icingadb"
MODULES_PATH="/usr/share/icingaweb2/modules"
MODULE_PATH="${MODULES_PATH}/${MODULE_NAME}"
RELEASES="https://github.com/${MODULE_AUTHOR}/${MODULE_NAME}/archive"
mkdir "$MODULE_PATH" \
&& wget -q $RELEASES/${MODULE_VERSION}.tar.gz -O - \
   | tar xfz - -C "$MODULE_PATH" --strip-components 1
icingacli module enable "${MODULE_NAME}"
```

Please advice, thanks! :)
